### ISSUE TITLE
Don't work with the new Madvr

### ISSUE THREAD

**Issue by magounet** [matthewn4444/Lightpack-Filter-and-API#1]
unfortunately, lightpack does not work with the new madVR ( exclusive Mode ) , do you know why ?

**Comment by matthewn4444** [comment]
I am using the most updated software for madvr, reclock, mph hc, lightpack filter and svp and have no issues. Please show me your configuration and observations. Also I'm using 32bit.

**Comment by Selur** [comment]
works fine here with latest MadVR & MPC-HC using 64bit
