### ISSUE TITLE
0.6.3 version doesn't even start for me

### ISSUE THREAD

**Issue by flagg19** [matthewn4444/Lightpack-Filter-and-API#3]
Hi, I just upgraded from 0.6.2 to 0.6.3 and the filter stopped working.
If I try to start _nw.exe_, apparently nothing happens except that in the task manager I can see three _nw.exe_ processes.

There's a text file called _debug.log_ in the installation directory, I don't know if its content can be of any use:

```
[0404/221520:INFO:nw_package.cc(175)] "C:\Program Files (x86)\Lightpack Filter\nw.exe"
[0404/221521:ERROR:image_metadata_extractor.cc(114)] Couldn't load libexif. 126
[0404/221551:ERROR:image_metadata_extractor.cc(114)] Couldn't load libexif. 126
[0404/221621:ERROR:image_metadata_extractor.cc(114)] Couldn't load libexif. 126
[0404/221815:INFO:nw_package.cc(175)] "C:\Program Files (x86)\Lightpack Filter\nw.exe"
[0404/221934:INFO:nw_package.cc(175)] "C:\Program Files (x86)\Lightpack Filter\nw.exe"
```

I tried uninstalling and re-installing, no luck.
Nothing even in the event viewer, I've no idea why it doesn't work.
Rolled back to 0.6.2 for now.

I'm on Windows 7 64bit.

**Comment by matthewn4444** [comment]
I see this issue, seems something to do with node webkit from Windows 10 vs Windows 7, I will try to fix it tonight.

**Comment by matthewn4444** [comment]
Just updated new version, works for me on Windows 7 now. Let me know if it works for you.

**Comment by flagg19** [comment]
Hi @matthewn4444 thanks for the quick reply.

The binaries aren't updated yet right?
If I try them I get the same results as yesterday (no windows shown, three processes in the task manager).

Compiling the sources gives some better results but still it doesn't fully work...
When I start _nw.exe_ this time it opens a windows with this content:

```
NW.JS nw.js v0.13.0
Node v5.9.0
Chromium 49.0.2623.87
commit hash: 45ba1e1-c4d99d5-3d99a78-5c8f26b
```

And... that's it, it doesn't go any further.
I compiled using the "easy" option.

**Comment by matthewn4444** [comment]
I just checked and it is working for me. I guess you already tried to uninstall and reinstall the new setup file? Maybe try again and delete your cached setup files.

If that doesnt work, you said you were able to successfully compile the project? I did some changes yesterday you can re-cloning the project and follow the easy steps to build the project by running the build script. Then download [http://dl.nwjs.io/v0.13.3/nwjs-sdk-v0.13.3-win-x64.zip](http://dl.nwjs.io/v0.13.3/nwjs-sdk-v0.13.3-win-x64.zip) and put the contents inside **/node.js/nw-binaries** replacing all the files inside. Then go to **/directshow/Lightpack-filter-gui** and **run compile.bat**. After that is done, go to /Release from root directory and edit the file **package.json**, change the part where it says **show: false** and change it to **show:true**. Then run nw.exe, it will open but there should be a javascript error. When opened press **f12** and it should open the debug chrome console. Go to the console tab and copy paste the error into your reply.

**Comment by flagg19** [comment]
Sorry, I was in a hurry and failed to see some error in the middle of the build script output, I saw the last message "Build is fully completed", the files where there, I assumed it worked. I'll try to fix whatever prevents me from fully build it as soon as I have time...

Anyway, yes, I tried to uninstall and reinstall the new setup file.
Not sure about the "cached setup files", Where can I find it?

> you can re-cloning the project and follow the easy steps to build the project by running the build script. Then download...

I'll try it when I'll be able to compile.
Assuming this makes any sense without the previous steps, I've tried changing **show** to **true** and that makes the GUI appear but it can't connect to lightpack.

**Comment by matthewn4444** [comment]
Did you download the [http://dl.nwjs.io/v0.13.3/nwjs-sdk-v0.13.3-win-x64.zip](http://dl.nwjs.io/v0.13.3/nwjs-sdk-v0.13.3-win-x64.zip) from previous instruction? That allows you to see the error when you change show to true. It won't connect because there is an error, once you can get that error message I can try to fix it.

**Comment by flagg19** [comment]
Ok I've managed to compile it without errors, here the output of the chrome debug console:

`Uncaught Error: Cannot find module './lightpack'`

PS: the problem I had compiling the project was that in both the `configure_win.py` files (app-mutex and lightpack) you try to open the visual studio project file with the extension ".vcproj" but the correct extension is ".vc**x**proj" (or at least that's the extension type I have on my PC).

**Comment by matthewn4444** [comment]
A few things. What version of Visual studio, nw-gypand node.js did you install? When you run `configure_win.py` it is suppose to generate a ".vcproj" file where the file is modified to get the module and the script upgrades it to ".vcxproj". This happens on my windows 7 and 10 machine. You can try running the script after deleting the **build** folder.

Anyways if you check /Release, is there a **lightpack.node**? If not it did not compile, you did something or changed the script too much.

Can you try this instead (and do not plug in the lightpack usb). 

1, Download the zip file [https://github.com/matthewn4444/Lightpack-Filter-and-API/releases/download/v0.6.3/lightpack-filter.zip](https://github.com/matthewn4444/Lightpack-Filter-and-API/releases/download/v0.6.3/lightpack-filter.zip), 
2. Extract it somewhere
3. Download the sdk version of nw.js [http://dl.nwjs.io/v0.13.3/nwjs-sdk-v0.13.3-win-x64.zip](http://dl.nwjs.io/v0.13.3/nwjs-sdk-v0.13.3-win-x64.zip)
4. Override all the files inside that folder (from step 2) with the nw.js sdk (from step 3)
5. Change the package.json of show from false to true
6. Run nw.exe and press f12
7. Output the error.

**Comment by flagg19** [comment]
- Visual studio Community Edition 2015 (version 14.0.25123.00 update 2)
- node-v5.10.0-x64
- nw-gup@0.13.0

Running `configure_win.py` crashes with the error:

```
Traceback (most recent call last):
  File "build.py", line 27, in <module>
    main()
  File "build.py", line 11, in main
    configure_win.main()
  File "C:\Users\MikeDev\Desktop\Lightpack-Filter-and-API\nodejs\ightpack\configure_win.py", line 21, in main
    with open("build/lightpack.vcproj", "r") as f:
IOError: [Errno 2] No such file or directory: 'build/lightpack.vcproj'
```

In /Release there's not **lightpack.node**, I guess it's because of the error in `configure_win.py`.

Anyways, I don't want to waste your time with my compile problems, using your binaries and the [nwjs-sdk-v0.13.3-win-x64.zip](http://dl.nwjs.io/v0.13.3/nwjs-sdk-v0.13.3-win-x64.zip) the error in the chrome console is:

```
Uncaught Error: %1 is not a valid Win32 application .
\\?\C:\Program Files (x86)\Lightpack Filter\app\node_modules\lightpack\lightpack.node
```

**Comment by matthewn4444** [comment]
You made sure you used new versions of the zip file the is on the site right?

This issue is now more related to node webkit as the nw-gyp doesnt seem to work. For some reason it works on my pc that runs windows 7?

Ok let's go back to compiling. Make sure you updated the submodules as I changed directshow 2 days ago (to be safe you could try to reclone the repo somewhere else).

We will do this manually.
1. Open terminal, bash shell or whatever to /node.js/lightpack.
2. Delete the build folder
3. Run `nw-gyp configure --target=0.13.0` and it should make a build folder (if no errors)
4. Open build folder and run the binding.sln in visual studio, it should upgrade the project
5. Change the solution to release (should already be win32, if not change it)
6. Right click the project in the solution explorer
7. Under **general**, make it look like below
   ![capture](https://cloud.githubusercontent.com/assets/1667384/14363709/716c6fd2-fcba-11e5-9e65-0f59130c3993.PNG)
8. Under **C/C++ > General**, add the following to the additional includes: `..\..\..\include`
9. Under **Linker > Input > Additional dependencies**, add `..\..\..\lib\lightpack.lib`
10. Same location as above, if you see `$(Configuration)\\nw.lib` as any of the other additional dependencies, please  change that part to `ia32\\nw.lib`. Repeat with `node.lib`

11, Now i think it should be ready to compile. Build the project and the output should be in **<root>/Release**

**Comment by flagg19** [comment]
The configuration created by `nw-gyp configure --target=0.13.0` is much different from yours, and even after adjusting everything I get some errors. I'll post a screenshot but it's in Italian...

![2016-04-07 21_57_21-mikedev in esecuzione - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/1681032/14365137/640749a0-fd0c-11e5-98ed-653bd24086ab.png)
I'll give a quick translation, from the top:
1. (already english)
2. Wrong match detected for 'RuntimeLibrary': the value 'MD_DynamicRelease' doens't match the value 'MT_StaticRelease' in lightpack.obj
3. Predefined library 'MSVCRT' is in conflict with other libraries, use /NODEFAULTLIB:library
4. external symbol '__imp_wcstombs' not resolved
5. same
6. and so on...

**Comment by flagg19** [comment]
Is it of any use to know that copying the `lightpack.node` from the working 0.6.2 installation to the broken 0.6.3 installation doesn't change the error?

```
Uncaught Error: %1 is not a valid Win32 application .
\\?\C:\Program Files (x86)\Lightpack Filter\app\node_modules\lightpack\lightpack.node
```

**Comment by matthewn4444** [comment]
You can't use 0.6.2 lightpack.node and 0.6.3 versions because the nw-gyp versions are different and not compatible.

I forgot to mention that you need to change the runtime, that should fix the build issues (I think). Here is an image:

![capture](https://cloud.githubusercontent.com/assets/1667384/14366564/288fede4-fcc8-11e5-926f-c674585a3316.PNG)

Also if you install nw-gyp before you need to uninstall it and reinstall it. If this was your first time you can ignore this (`npm uninstall -g nw-gyp && npm install -g nw-gyp`)

**Comment by flagg19** [comment]
> ... If this was your first time you can ignore this...

It was.

Ok now it compiles, it creates `lightpack.node` in the release directory, but even if I use it instead of the one that come with the compiled binaries the error is the same.

```
Uncaught Error: %1 is not a valid Win32 application .
\\?\C:\Program Files (x86)\Lightpack Filter\app\node_modules\lightpack\lightpack.node
```

The windows 7 machine that you used to try it is 64 or 32 bit? Mine is 64 bit.

**Comment by matthewn4444** [comment]
I am running Windows 64 bit. That is weird are you sure you are running 64bit?

I am not sure about your coding skills but can you try to compile this example?

https://github.com/nodejs/node-v0.x-archive/tree/master/test/addons/hello-world

Maybe nw-gyp doesnt work exclusively for you?
1. Download 3 files
2. run  `nw-gyp configure --target=0.13.0` in terminal
3. Open the sln inside build folder with visual studio 15
4. compile it (if there are errors you may need to change the runtime from the prevous post)
5. Run the test script `node ./test.js`

**Comment by flagg19** [comment]
> That is weird are you sure you are running 64bit?

Yes, totally.

> I am not sure about your coding skills but can you try to compile this example?

I'll try this weekend, my c/c++/visual studio skills are quite low as you can see ;)

I'll add just another information. My main PC, connected to my Lightpack, runs windows 7 64bit. The machine I use for development is a virtual machine (virtualbox) hosted on the main PC, and even the virtual machine guest runs windows 7 64bit. Running the 0.6.3 version on the virtual machine gives the exact same error (`Uncaught Error: %1 is not a valid Win32 application .`) that I have when I try to run it on my main PC. The virtual machine can't see the Lightpack device, but I was expecting a different error. Can not having a Lightpack device connected produce that error? If not, than I have two logically different machines (different install dvd, different software, different level of windows updates...) that behaves the same about this error.

I don't have another physical windows machine to try it onto, just out of curiosity I will try it on my win 8 pc at work next monday.

**Comment by matthewn4444** [comment]
Ok. I ran this on my desktop that has 10, also my laptop that has 10 and my work laptop that has 7 64bit. I haven't tried virtual machine. If you can build and run the hello world app from instructions above then it is possible to fix, if not it seems you can't run it. But you were able to run 0.6.2?

**Comment by flagg19** [comment]
0.6.2 always worked flawlessly (and it's still working right now as I'm writing), tomorrow or the day after tomorrow I'll try that hello world.

**Comment by matthewn4444** [comment]
So ironic when I decided to update the code to work with a newer version it breaks everything (thanks to unstable libraries). If that hello world doesn't work might try to revert or find a version that works, and communicate through email rather than here on github

**Comment by ranarn** [comment]
Got same issue on win10 :(

**Comment by matthewn4444** [comment]
ranarn, can you run 0.6.2?

**Comment by ranarn** [comment]
Yes 0.6.2 works fine, and have always done so.

**Comment by matthewn4444** [comment]
If you guys are willing to help out, I can send you a version now to see if it runs on your system. I just updated the code to work on a PC I have that was able to reproduce the failure. I am working on fixing the rest of the bugs and should have a new version up soon (in a week or less), sorry for the wait.

**Comment by ranarn** [comment]
Yes, absolutely. (will try when i get home from work in the end of the day).

**Comment by matthewn4444** [comment]
Check releases for 0.6.4a and setup using the zip file. You can let me know if you are able to open the filter configurations or not.

**Comment by ranarn** [comment]
I can confirm now that it works as intended on Windows 10.
Great job!

**Comment by matthewn4444** [comment]
Great, will have a full version up soon with an installer. Coding this bug.
